### ISSUE TITLE
Clarification needed regarding to Services and Functions

### ISSUE THREAD

**Issue by borditamas** [eclipse-arrowhead/documentation#3]
As stated in the Reference Model:

> A service is an identifiable set of functions provided by a system, allowing for other systems to trigger its
capabilities by sending messages to, or invoking, those functions. The act of sending a message to a certain
function is referred to as consuming its service. 

I understand that at the end of orchestration process the consumer system will call/trigger the function. But what is not fully clear for me due to this definition that how the orchestration process should happen .

**Shall the consumers orchestrate for the services or for the functions?**

Do the functions have specific names similarly like the services have? Or how the consumer will be able to decide that which function is the required one?

**Comment by emanuelpalm** [comment]
I'm working on a new draft of the reference model proposal, and the term "function" will change name to "operation".

It has always been the case that a service is what could be thought of as a class or interface in a programming language like Java (which can have any number of methods), even if there has been quite some confusion about it.
Just as you cannot use a Java class without specifying what method to call, you cannot consume a service without specifying what operation to invoke. The point of the reference model (which also changes name to "core concepts") is to remove confusion like this.

The service is a set of operations that are either provided all at once or not at all. They should be related in what they are meant to accomplish. A service consumer should in most cases be assumed to know of all the operations associated with each specific service type (identified by a service name/identifier). I would, therefore, assume that orchestration operates at the level of service, an not at the level of individual operations.

**Comment by borditamas** [comment]
Thanks for the clarification!

It is really important to have a clear and agreed definition on this, because it has been always a big gap between the conception and the implementation (or at least since v4.1.2 which after we took over the java implementation).

For example most often we run into confusions regarding to  `service-discovery` service. The concept which can be found in the documentations is that it has `register`, `unregister`, etc... functions, but for some reason the eariler inplementations ended up with not having `service-discovery` service, but having `register` , `unregiset` etc... services. 

Maybe the concept of Authorization could be a reason considering that it is operating also on the service level. Which means that having an authorization rule for a consumer to a service allows the consumer to consume all the operations. And I can imagine that it's not always the desired way of working.

Also I don't remember having seen such terms like "function-identifier" or "function-name" in the docs, which obviously would need for the consumer to being able to pick the required function (operation) form the orchestration response.

**Comment by emanuelpalm** [comment]
@borditamas Yes, the v4.1.2 implementation you inherited was incorrect. This caused me quite some confusion in the beginning, but after some discussions with @jerkerdelsing some years ago, I learned that it was the implementation that was incorrect and not my understanding. If you look in the _IoT Automation: Arrowhead Framework_ book, it defines __service__ as a _"group of capabilities"_ on page 46, without specifying what is meant by _"capabilities"_. I think that small ambiguities like this is what added up to the original confusion. Jerker worked in the office just across the hall from mine, so I was able to catch him and ask questions better than I think you have been able to in Hungary. :P

Yes, authorization works at the granularity of whole services (if an auth-rule says you can consume a service, you are allowed to invoke all of its functions/operations). This is meant to change with the introduction of [NGAC-based authentication](http://ltu.diva-portal.org/smash/get/diva2:1461827/FULLTEXT01.pdf) in Arrowhead, which should be able to work at the granularity of individual calls to individual service functions/operations. I'm not sure when this will happen. 

Functions/operations do not need to have unique identifiers. Assume, for example, that a particular system provides a service with the _instance identifier_ `"xyz-123"` and the _type identifier_ `"service-registration"`. If a system is to be able to consume this service, it must be implemented as described by an IDD associated with that service _type identifier_. The IDD will refer to a protocol stack, such as HTTPS/JSON, and describe how to interact with each of the operations of a service of that type (what data to include in the payload, what method and path to specify, etc.). It could, for example, be the case that the IDD describes two operations, which could be realized as the HTTP endpoints `POST /entries` and `DELETE /entries`. The service registry entry describing service `"xyz-123"` could also indicate that a certain base path be used to access the operations, such as `/service-registration`, which means that invoking the first operation would require sending a message with the method and path `POST /service-registration/entries`.

**Comment by borditamas** [comment]
Sticking to your example I assume that all the provider which wants to provide the `service-registration` service and its operations via HTTP/JSON have to use the same method and the path with mandatory segment such as `POST /{base-path}/entries` for register operation because the IDD stated so.  Do I understand well?

I agree that in case of HTTP protocol the method have to be defined by the IDD, but I would allow to use fully custom paths.

Similarly in case of messaging protocols I would not obligate the providers to use the same topic or queue names. It could cause troubles when providers are using a common broker and for example not using "base-path kind" part in the name. So a fully custom access path with an "operation-name" which is unique in scope of the service could be useful in these kind of issues.

Another aspect that ServiceRegistry should be able to verify if a provider provides all the operations of the service at registration time. Therefore SR have to know in advance what operations are belonged to a service independently from the interfaces.

**Comment by emanuelpalm** [comment]
> Sticking to your example I assume that all the provider which wants to provide the service-registration service and its operations via HTTP/JSON have to use the same method and the path with mandatory segment such as POST /{base-path}/entries for register operation because the IDD stated so. Do I understand well?

No. My explanation was probably not good enough. ;-) The `/service-registration` base path can vary with every instance of the service. They only need to be different, however, on service instances provided by the same system.

Every service is provided by a system, which is hosted by a device. When you send a message to a service operation, that message must identify (1) a network interface on the device, (2) the system providing the service, (3) the service itself, and (4) the service operation. How that identification is carried out does not matter, as long as it works and is well-documented.

Consider an example where an HTTP message is sent to a service. HTTP is defined as an extension of the TCP protocol, which is an extension of the IP protocol. I know you already know this, but please follow along anyway. Sending an HTTP message requires (1) an IP address, (2) a TCP port number, and (3) HTTP headers. The IP address identifies a network interface on the device receiving the message. The port number has been allocated by a system hosted by that device (a system may, of course, allocate any number of ports), which makes the network interface able to forward the message to a system interface (if your system runs on an operating system, the system interface will receive the message through a binding between a port number and a process ID). The system interface may have its own internal mapping between port numbers and service interfaces, or may use some other information in the HTTP headers to identify a service interface. Let us assume that the combination of port number and HTTP base path is used to map messages to service interfaces. When the service interface receives the message, it may, for example, use the method and path of the message, in combination, to map the message to an operation interface. That operation interface decodes and validates the message body and then executes the operation itself with the message body as argument.

In other words, every message must contain enough information such that the correct next entity can be selected at each of the below phases:

```
Device -> System -> Service -> Operation
```

Every arrow represents a one-to-many relationship.

> I agree that in case of HTTP protocol the method have to be defined by the IDD, but I would allow to use fully custom paths.
>
> Similarly in case of messaging protocols I would not obligate the providers to use the same topic or queue names. It could cause troubles when providers are using a common broker and for example not using "base-path kind" part in the name. So a fully custom access path with an "operation-name" which is unique in scope of the service could be useful in these kind of issues.

Anything you like can be custom, as long as their is a way to identify each service operation independent of the thing that is custom for the service instance. You could even use a query parameter to identify what service operation is being targeted, but I advice against it. The mapping between service operations and HTTP header information should be obvious to those with experience with HTTP. If you use MQTT, AMQP or some other protocol you also have to make up your own routing scheme.

> Another aspect that ServiceRegistry should be able to verify if a provider provides all the operations of the service at registration time. Therefore SR have to know in advance what operations are belonged to a service independently from the interfaces.

No. The service registry should not be concerned with if every service operation associated with every service type is being provided by each service instance. Knowing that a particular operation is available is hardly helpful, because it does not tell you if the method actually does what it is supposed to do. Also, how would the service registry know about all the service operations? The consumer of a particular service type is expected to already know of all operations provided by instances of that service type. Making the service registry able to validate all service operations would require (1) that it maintains a registry of service types in addition to service instances (as it does today), and (2) is told what messages to use when testing each service operation and how to determine if a received response does indicate that the operation is behaving as expected. If this is something we want, I suggest we have a system dedicated to checking service operations rather than having the service registry do it.

**Comment by borditamas** [comment]
I have to admit, I'm a bit confused :) Probably beacuse I try to interpret this from the implementation view and my arrowhead fundamentals are mostly coming from the current java implementation.

> The /service-registration base path can vary with every instance of the service.

That's how I did understand too. :) But still there is `/entries` path part which I thought is mandatory to use in case of HTTP stack and was wondering  why not could use a provider system a completly different path if it wants to for whatever reason. But now I assume it could use, but that would be an another IDD with the same protocol stack, right?

Anyway, it is really a bit confusing that an operation - which could have multiple interfaces - are identified by the interfaces themselves. And the consumer which are able to send a http/json message to  `POST /{base-path}/entries` would be also able to send it for example to `POST /{base-path}/services` without having the `POST /entries` and `POST /services` implemented as a different interface. (I'm afraid service-registration is no the best example for this...). 

>  Consider an example where an HTTP message is sent to a service...

My concern is not really about how the message will be identified by the provider side, but how the consumer system will efficiently orcestrate for and consume the required service operation. According to your example I belive that the interface descriptor values have to be hard-coded into the consumer instead of the IDD would describe only that what descriptors have to be used( without specifying the values) such as method, path and json structure for HTTP-JSON as an example. 

> No. The service registry should not be concerned with if every service operation associated with every service type is being provided by each service instance. Knowing that a particular operation is available is hardly helpful, because it does not tell you if the method actually does what it is supposed to do.

That's true, but you also said that _"The service is a set of operations that are either provided all at once or not at all"._ If SR could check whether the porvider system provides at least one interface for each operation, then we would programmatically do something in order to force providers to comply with this rule.

> would require (1) that it maintains a registry of service types in addition to service instances (as it does today)

Yes, but with the difference that it would also require the System Operator to add the service types in advance. It would mean, that the System Operator has full control on what kind of service types are allowed to provide within the cloud. I'm not saying that this is how it have to work, but could be a valid scenario.

> and (2) is told what messages to use when testing each service operation and how to determine if a received response does indicate that the operation is behaving as expected.

I agree that testing the actual behavior of a service operation is not a registry related feature. But verifying the registry entry itself (including the presence of all the operations) is definitely a registry related responsibility.

**Comment by emanuelpalm** [comment]
> I have to admit, I'm a bit confused :) Probably beacuse I try to interpret this from the implementation view and my arrowhead fundamentals are mostly coming from the current java implementation.
>
>>    The /service-registration base path can vary with every instance of the service.
>
>That's how I did understand too. :) But still there is /entries path part which I thought is mandatory to use in case of HTTP stack and was wondering why not could use a provider system a completly different path if it wants to for whatever reason. But now I assume it could use, but that would be an another IDD with the same protocol stack, right?

Yes. The `/entries` part is defined by the IDD and can be whatever you like. You may also differentiate between services and operations using other data in the HTTP header, as long as you specify how in the IDD. I, however, recommend sticking to having base paths mapping to service instances and the remaining path mapping to operations, just as we have been saying already. ;-)

> Anyway, it is really a bit confusing that an operation - which could have multiple interfaces - are identified by the interfaces themselves. And the consumer which are able to send a http/json message to POST /{base-path}/entries would be also able to send it for example to POST /{base-path}/services without having the POST /entries and POST /services implemented as a different interface. (I'm afraid service-registration is no the best example for this...).

Why is it confusing that the interface is identified instead of the operation? The interface represents what a consumer can actually access. The operation itself can only be accessed directly (not via an interface) by the system providing it.

While you indeed could provide the same operation via more than one interface, I don't believe many will do it via more than one interface implemented on top of HTTP. You could provide access to the same operation via MQTT, CoAP, AMQP, and so on, to make it easier to cater to different use cases and devices. I guess you could have one high-priority HTTP interface and another low-priority HTTP interface, and provide stronger real-time/latency guarantees with the former, and so on.

>>    Consider an example where an HTTP message is sent to a service...
> 
> My concern is not really about how the message will be identified by the provider side, but how the consumer system will efficiently orcestrate for and consume the required service operation. According to your example I belive that the interface descriptor values have to be hard-coded into the consumer instead of the IDD would describe only that what descriptors have to be used( without specifying the values) such as method, path and json structure for HTTP-JSON as an example.

I'm not certain I understand your point. Indeed, yes, the IDD specifies how to address the individual operations associated with the service type. Without the information in the IDD you cannot meaningfully communicate with a particular service type. The IDD is not required to be a human-readable document, however. It could just as well be a programmatic description, expressed  in, for example, JSON or SysML. When I later finish the Arrowhead documentation reference, I will be able to describe this in greater detail.

>> No. The service registry should not be concerned with if every service operation associated with every service type is being provided by each service instance. Knowing that a particular operation is available is hardly helpful, because it does not tell you if the method actually does what it is supposed to do.
>
> That's true, but you also said that "The service is a set of operations that are either provided all at once or not at all". If SR could check whether the porvider system provides at least one interface for each operation, then we would programmatically do something in order to force providers to comply with this rule.

I guess this is a matter of what we consider the scope of the service registry itself. I would argue that verifying that service instances conform to their service types is a problem for another system, but I'm not going to be stubborn about it at this point.

>> would require (1) that it maintains a registry of service types in addition to service instances (as it does today)
>
> Yes, but with the difference that it would also require the System Operator to add the service types in advance. It would mean, that the System Operator has full control on what kind of service types are allowed to provide within the cloud. I'm not saying that this is how it have to work, but could be a valid scenario.

This is an interesting point. To be able to whitelist or blacklist service types is something I haven't considered before. Perhaps something to remember for later? :)

>> and (2) is told what messages to use when testing each service operation and how to determine if a received response does indicate that the operation is behaving as expected.
>
> I agree that testing the actual behavior of a service operation is not a registry related feature. But verifying the registry entry itself (including the presence of all the operations) is definitely a registry related responsibility.

It could be. In my mind the service registry is just that, a _registry_. Registries do not keep themselves up to date. They create, update, maintain, provide and delete data records as requested. If we want to check if systems are live or not, that should, in my mind, be done by a different system. That system may, of course, be part of the same binary or JAR as the service registry, but can be turned on or off independently of the service registry itself.

**Comment by emanuelpalm** [comment]
@borditamas Do you have any further questions or can be consider this discussion concluded?

**Comment by borditamas** [comment]
@emanuelpalm No further questions, many thanks for the clarification.
