### ISSUE TITLE
Make pdf's of the documents directly available 

### ISSUE THREAD

**Issue by jerkerdelsing** [eclipse-arrowhead/documentation#5]
Please compile pdf's for all documents written I Latex

**Comment by tsvetlin** [comment]
Very good idea, allows a quick preview of the given document!

**Comment by emanuelpalm** [comment]
https://github.com/eclipse-arrowhead/documentation/releases (click the Assets button).

I've added a link to the README.md file, which you can see at https://github.com/eclipse-arrowhead/documentation/. I want to avoid adding binary files to the GIT repository as much as I can.

**Comment by jerkerdelsing** [comment]
I would still argue that a pdf should be added to the source.
This since it is a documentation repo. Not code repo for documents.

**Comment by emanuelpalm** [comment]
@jerkerdelsing I must confess that my idea was for it to be just a "code repo for documents". The problem with storing binary files in a Git repo is that is is going to explode in download size.

Rather than storing binary files in Git, we should rather let people download them from the arrowhead.eu website. We could setup a [GitHub Action](https://github.com/features/actions) to automatically upload the compiled PDF:s to the arrowhead.eu website whenever a new commit is pushed to the repository, for example.

**Comment by jerkerdelsing** [comment]
Since we don't have such mechanism for publishing the pdf's on the web yet I think we very much need to store the pdf's in the GitHub repo.
